import type { Metadata } from "next";
import { DataProvider } from "@/context/DataContext";
import Providers from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
          <link
              href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:wght@400;700&display=swap"
              rel="stylesheet"
          />
      </head>
      <body>
      <DataProvider>
        <Providers>
              {children}
        </Providers>
      </DataProvider>
      </body>
    </html>
  );
}
